@startuml Class_Diagram
left to right direction

package "Restaurant" {
    class "<<Application>>\nRestaurantService" as RestaurantService {}

    class "<<Resource>>\nrestaurants" as ResourceRestaurants {
        <<GET>> +getRestaurants(): Restaurant
        <<POST>> +createRestaurant(): Restaurant
    }

    class "<<Resource>>\nrestaurant" as ResourceRestaurant {
        <<GET>> +getRestaurant(): Restaurant
        <<PUT>> +updateRestaurant(): Restaurant
        <<DELETE>> +deleteRestaurant(): void
    }

    class "<<Representation>>\nRestaurant" as RepresentationRestaurant {
        -name: String
        -address: String
        -tel: String
        -open_time: String
        -close_time: String
    }
}

package "Reservation" {
    class "<<Application>>\nReservationService" as ReservationService {}

    class "<<Resource>>\nreservations" as ResourceReservations {
        <<GET>> +getReservations(): Reservation
        <<POST>> +addReservation(): Reservation
    }

    class "<<Resource>>\nreservation" as ResourceReservation {
        <<GET>> +getReservation(): Reservation
        <<PUT>> +updateReservation(): Reservation
        <<DELETE>> +deleteReservation(): void
    }

    class "<<Representation>>\nReservation" as RepresentationReservation {
        -reserDate: Date
        -user: User
        -restaurant: Restaurant
        -createdAt: Date
    }
}

package "User" {
    class "<<Application>>\nAuthService" as AuthService {}

    class "<<Resource>>\nauth" as ResourceAuth {
        <<POST>> +register(): User
        <<POST>> +login(): User
        <<POST>> +logout(): void
        <<GET>> +getMe(): User
    }

    class "<<Representation>>\nUser" as RepresentationUser {
        -name: String
        -email: String
        -role: String
        -password: String
        -tel: String
        -createdAt: Date
    }
}

RestaurantService ..> ResourceRestaurants : "/restaurants\n<<Path>>"
ResourceRestaurants ..> ResourceRestaurant : "/{restaurantId}\n<<Path>>"
ResourceRestaurant ..> RepresentationRestaurant : "<<use>>"

ReservationService ..> ResourceReservations : "/reservations\n<<Path>>"
ResourceReservations ..> ResourceReservation : "/{reservationId}\n<<Path>>"
ResourceReservation ..> RepresentationReservation : "<<use>>"

AuthService ..> ResourceAuth : "/auth\n<<Path>>"
ResourceAuth ..> RepresentationUser : "<<use>>"

@enduml
